services:
  web:
    image: omar077/students-spring-react:latest
    ports:
      - "80:8080"
    restart: "always"
  db:
    image: postgres:15-alpine
    volumes:
      - "/home/omar/data:/var/lib/postgresql/data"

networks:
  db:
